//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.secure
{


    public partial class cambios_empleado
    {

        protected global::System.Web.UI.UpdatePanel PanelInfomacion;
        protected global::System.Web.UI.WebControls.GridView gvCambios;
        protected global::System.Web.UI.WebControls.Label lblFechaMov;
        protected global::System.Web.UI.WebControls.Label lblDesCambios;

    
    }
}
