using System;
// ...existing using statements...
namespace web.secure
{
    public partial class verempleado : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            // ...existing code to get 'legajo' from query params...
            // ...populate fields from BLL/Entities...
            // ...no methods for creating/updating, only data display...
        }
        // ...no event handlers for saving changes...
    }
}
